### ISSUE TITLE
crypto_sign_open() does not verify signature

### ISSUE THREAD

**Issue by sandboxgames** [iost-official/java-sdk#4]
It seems like the crypto_sign_open() method does not verify the signature correctly (or not at all). The result code from TweetNaCl.crypto_sign_open(message, signed, signed.length, publicSigningKey) is not used. The code as seen below, throw InvalidSignatureException.
```java
        String message = "hello world";
        KeyPair k = new Ed25519();

        System.out.println(k.B58SecKey());
        System.out.println(k.B58PubKey());


        byte[] signMessage = TweetNaCl.crypto_sign(message.getBytes(), k.seckey());
        byte[] openMessage = TweetNaCl.crypto_sign_open(signMessage, k.pubkey());


        System.out.println(new String(signMessage));
        System.out.println(new String(openMessage));
```

**Comment by KePeng1019** [comment]
> It seems like the crypto_sign_open() method does not verify the signature correctly (or not at all). The result code from TweetNaCl.crypto_sign_open(message, signed, signed.length, publicSigningKey) is not used. The code as seen below, throw InvalidSignatureException.
> 
> ```java
>         String message = "hello world";
>         KeyPair k = new Ed25519();
> 
>         System.out.println(k.B58SecKey());
>         System.out.println(k.B58PubKey());
> 
> 
>         byte[] signMessage = TweetNaCl.crypto_sign(message.getBytes(), k.seckey());
>         byte[] openMessage = TweetNaCl.crypto_sign_open(signMessage, k.pubkey());
> 
> 
>         System.out.println(new String(signMessage));
>         System.out.println(new String(openMessage));
> ```

you should append message to signedMessage to verify it .
```java
byte[]  meesageWithSignture = new byte[signMessage.length + meesage.getBytes().length]
System.arraycopy(signMessage, 0, meesageWithSignture, 0, signMessage.length);
System.arraycopy(meesage.getBytes(), 0, meesageWithSignture,  signMessage.length, meesage.getBytes().length);
byte[] openMessage = TweetNaCl.crypto_sign_open(meesageWithSignture, k.pubkey());
 ```

**Comment by sandboxgames** [comment]
oh, got it. it work!
